services:
  db_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
    ports:
      - "3307:3306"
    networks:
      - red_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app_persona:
    image: backend-app:latest
    depends_on:
      db_mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - red_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/miapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  red_net:
    driver: bridge
