version: "3.9"
services:
  db_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
    ports:
      - "3307:3306"
    networks:
      - red_net

  app_persona:
    build: .
    depends_on:
      - db_mysql
    ports:
      - "8080:8080"
    networks:
      - red_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/miapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  red_net:
    driver: bridge